"""
02b_clean_population_metadata.py
--------------------------------------------------
Adds TCGA race and ethnicity annotations to the phenotype table generated by
02_clean_phenotype.py.

The full UCSC Xena GDC phenotype file contains repeated case information because
clinical, diagnosis, exposure, and sample entities are flattened together. This
script therefore resolves race and ethnicity at patient level before joining the
annotations back to sample-level metadata.

Inputs:
    data/raw/pheno_clean.parquet
    data/raw/GDC-PANCAN.GDC_phenotype.tsv.gz

Outputs:
    data/raw/pheno_population.parquet
    data/raw/patient_population_metadata.parquet
    data/raw/population_metadata_conflicts.csv
--------------------------------------------------
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import pandas as pd
import requests


ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data" / "raw"
DATA_DIR.mkdir(parents=True, exist_ok=True)

BASIC_PHENO_PATH = DATA_DIR / "pheno_clean.parquet"
FULL_PHENO_PATH = DATA_DIR / "GDC-PANCAN.GDC_phenotype.tsv.gz"
OUTPUT_PATH = DATA_DIR / "pheno_population.parquet"
PATIENT_OUTPUT_PATH = DATA_DIR / "patient_population_metadata.parquet"
CONFLICT_OUTPUT_PATH = DATA_DIR / "population_metadata_conflicts.csv"

FULL_PHENOTYPE_URL = (
    "https://gdc-hub.s3.us-east-1.amazonaws.com/download/"
    "GDC-PANCAN.GDC_phenotype.tsv.gz"
)

MISSING_LABELS = {
    "",
    "--",
    "na",
    "n/a",
    "nan",
    "none",
    "null",
    "unknown",
    "not reported",
    "not allowed to collect",
    "not applicable",
}

RACE_MAP = {
    "asian": "Asian",
    "white": "White",
    "black or african american": "Black or African American",
    "american indian or alaska native": "American Indian or Alaska Native",
    "native hawaiian or other pacific islander": (
        "Native Hawaiian or Other Pacific Islander"
    ),
    "more than one race": "More than one race",
}

ETHNICITY_MAP = {
    "hispanic or latino": "Hispanic or Latino",
    "not hispanic or latino": "Not Hispanic or Latino",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Add race/ethnicity metadata to pheno_clean.parquet."
    )
    parser.add_argument(
        "--basic-phenotype",
        type=Path,
        default=BASIC_PHENO_PATH,
        help="Phenotype parquet generated by 02_clean_phenotype.py.",
    )
    parser.add_argument(
        "--full-phenotype",
        type=Path,
        default=FULL_PHENO_PATH,
        help="Full UCSC Xena GDC phenotype TSV or TSV.GZ.",
    )
    parser.add_argument(
        "--download-url",
        default=FULL_PHENOTYPE_URL,
        help="URL used when --full-phenotype does not exist.",
    )
    parser.add_argument(
        "--force-download",
        action="store_true",
        help="Download the full phenotype again even if the file exists.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help="Output sample-level phenotype parquet.",
    )
    parser.add_argument(
        "--patient-output",
        type=Path,
        default=PATIENT_OUTPUT_PATH,
        help="Output patient-level population metadata parquet.",
    )
    parser.add_argument(
        "--conflict-output",
        type=Path,
        default=CONFLICT_OUTPUT_PATH,
        help="CSV report for patients with conflicting demographic values.",
    )
    parser.add_argument(
        "--strict-conflicts",
        action="store_true",
        help="Stop instead of assigning Unknown when conflicts are detected.",
    )
    return parser.parse_args()


def download_file(url: str, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = output_path.with_suffix(output_path.suffix + ".part")

    print(f"Downloading full phenotype:\n  {url}")
    with requests.get(url, stream=True, timeout=120) as response:
        response.raise_for_status()
        with temporary_path.open("wb") as handle:
            for chunk in response.iter_content(chunk_size=1024 * 1024):
                if chunk:
                    handle.write(chunk)

    temporary_path.replace(output_path)
    print(f"Saved: {output_path}")


def first_existing(columns: Iterable[str], candidates: Iterable[str]) -> str | None:
    available = set(columns)
    return next((candidate for candidate in candidates if candidate in available), None)


def clean_scalar(value: object) -> str | None:
    if pd.isna(value):
        return None
    text = str(value).strip()
    if text.lower() in MISSING_LABELS:
        return None
    return text


def normalize_category(value: object, mapping: dict[str, str]) -> str | None:
    cleaned = clean_scalar(value)
    if cleaned is None:
        return None
    key = " ".join(cleaned.lower().split())
    return mapping.get(key, cleaned)


def patient_id_from_barcode(series: pd.Series) -> pd.Series:
    return (
        series.astype("string")
        .str.strip()
        .str.split("-")
        .str[:3]
        .str.join("-")
    )


def resolve_patient_values(
    full: pd.DataFrame,
    patient_col: str,
    value_col: str,
    output_col: str,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    records: list[dict[str, object]] = []
    conflicts: list[dict[str, object]] = []

    for patient_id, values in full.groupby(patient_col, sort=False)[value_col]:
        unique_values = sorted({value for value in values.dropna().tolist() if value})

        if len(unique_values) == 0:
            resolved = "Unknown"
        elif len(unique_values) == 1:
            resolved = unique_values[0]
        else:
            resolved = "Unknown"
            conflicts.append(
                {
                    "patient_id": patient_id,
                    "field": output_col,
                    "values": " | ".join(unique_values),
                    "n_distinct": len(unique_values),
                }
            )

        records.append({"patient_id": patient_id, output_col: resolved})

    return pd.DataFrame(records), pd.DataFrame(conflicts)


def detect_compression(path: Path) -> str | None:
    """Detect compression from file magic bytes instead of the filename.

    Some UCSC Xena downloads are returned already decompressed even though the
    requested filename ends in .gz. In that situation, pandas compression="infer"
    incorrectly attempts to open the plain TSV as gzip and raises BadGzipFile.
    """
    with path.open("rb") as handle:
        magic = handle.read(4)

    if magic.startswith(b"\x1f\x8b"):
        return "gzip"
    if magic.startswith(b"PK\x03\x04"):
        return "zip"
    if magic.startswith(b"BZh"):
        return "bz2"
    if magic.startswith(b"\xfd7zXZ"):
        return "xz"
    return None


def read_phenotype_tsv(
    path: Path,
    *,
    nrows: int | None = None,
    usecols: list[str] | None = None,
    dtype: str | dict[str, str] | None = None,
    low_memory: bool = False,
) -> pd.DataFrame:
    compression = detect_compression(path)
    format_label = compression or "plain TSV"
    print(f"Detected phenotype format: {format_label}")

    return pd.read_csv(
        path,
        sep="\t",
        nrows=nrows,
        usecols=usecols,
        dtype=dtype,
        compression=compression,
        low_memory=low_memory,
    )


def load_full_population_metadata(path: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    header = read_phenotype_tsv(path, nrows=0)

    sample_col = first_existing(header.columns, ["sampleID", "sample", "samples.submitter_id"])
    race_col = first_existing(header.columns, ["demographic.race", "race"])
    ethnicity_col = first_existing(
        header.columns,
        ["demographic.ethnicity", "ethnicity"],
    )

    missing = [
        name
        for name, value in {
            "sample identifier": sample_col,
            "race": race_col,
            "ethnicity": ethnicity_col,
        }.items()
        if value is None
    ]
    if missing:
        raise KeyError(
            "The full phenotype is missing required fields: "
            + ", ".join(missing)
            + f". Available columns include: {header.columns.tolist()[:30]}"
        )

    usecols = [sample_col, race_col, ethnicity_col]
    full = read_phenotype_tsv(
        path,
        usecols=usecols,
        dtype="string",
        low_memory=False,
    ).rename(
        columns={
            sample_col: "sample_id_full",
            race_col: "race_source",
            ethnicity_col: "ethnicity_source",
        }
    )

    full["patient_id"] = patient_id_from_barcode(full["sample_id_full"])
    full = full[full["patient_id"].str.match(r"^TCGA-[A-Z0-9]{2}-[A-Z0-9]{4}$", na=False)].copy()

    full["race_normalized"] = full["race_source"].map(
        lambda value: normalize_category(value, RACE_MAP)
    )
    full["ethnicity_normalized"] = full["ethnicity_source"].map(
        lambda value: normalize_category(value, ETHNICITY_MAP)
    )

    race_table, race_conflicts = resolve_patient_values(
        full,
        patient_col="patient_id",
        value_col="race_normalized",
        output_col="race",
    )
    ethnicity_table, ethnicity_conflicts = resolve_patient_values(
        full,
        patient_col="patient_id",
        value_col="ethnicity_normalized",
        output_col="ethnicity",
    )

    patient = race_table.merge(
        ethnicity_table,
        on="patient_id",
        how="outer",
        validate="one_to_one",
    )
    patient["race"] = patient["race"].fillna("Unknown")
    patient["ethnicity"] = patient["ethnicity"].fillna("Unknown")
    patient["race_reported"] = patient["race"].ne("Unknown")
    patient["is_asian"] = patient["race"].eq("Asian")
    patient["population_group"] = "Non-Asian"
    patient.loc[patient["is_asian"], "population_group"] = "Asian"
    patient.loc[~patient["race_reported"], "population_group"] = "Unknown"

    conflicts = pd.concat(
        [race_conflicts, ethnicity_conflicts],
        ignore_index=True,
    )
    return patient, conflicts


def validate_basic_phenotype(basic: pd.DataFrame) -> pd.DataFrame:
    required = {
        "sample_id",
        "patient_id",
        "tumor_type",
        "tissue_type",
        "sample_class",
    }
    missing = sorted(required.difference(basic.columns))
    if missing:
        raise KeyError(
            "pheno_clean.parquet is missing required columns: " + ", ".join(missing)
        )

    out = basic.copy()
    out["sample_id"] = out["sample_id"].astype("string").str.strip()
    out["patient_id"] = out["patient_id"].astype("string").str.strip()

    duplicate_samples = out["sample_id"].duplicated(keep=False)
    if duplicate_samples.any():
        examples = out.loc[duplicate_samples, "sample_id"].head(10).tolist()
        raise ValueError(f"Duplicate sample_id values in pheno_clean.parquet: {examples}")

    return out


def main() -> None:
    args = parse_args()

    if not args.basic_phenotype.exists():
        raise FileNotFoundError(
            f"Missing {args.basic_phenotype}. Run pipelines/02_clean_phenotype.py first."
        )

    if args.force_download or not args.full_phenotype.exists():
        download_file(args.download_url, args.full_phenotype)

    print(f"Loading basic phenotype: {args.basic_phenotype}")
    basic = validate_basic_phenotype(pd.read_parquet(args.basic_phenotype))

    print(f"Loading population metadata: {args.full_phenotype}")
    patient, conflicts = load_full_population_metadata(args.full_phenotype)

    if not conflicts.empty:
        args.conflict_output.parent.mkdir(parents=True, exist_ok=True)
        conflicts.to_csv(args.conflict_output, index=False)
        print(f"Population conflicts: {len(conflicts):,}")
        print(f"Conflict report: {args.conflict_output}")
        if args.strict_conflicts:
            raise ValueError(
                "Conflicting patient-level demographic values were detected. "
                "Review the conflict report before continuing."
            )
    elif args.conflict_output.exists():
        args.conflict_output.unlink()

    enriched = basic.merge(
        patient,
        on="patient_id",
        how="left",
        validate="many_to_one",
    )

    enriched["race"] = enriched["race"].fillna("Unknown")
    enriched["ethnicity"] = enriched["ethnicity"].fillna("Unknown")
    enriched["race_reported"] = enriched["race"].ne("Unknown")
    enriched["is_asian"] = enriched["race"].eq("Asian")
    enriched["population_group"] = "Non-Asian"
    enriched.loc[enriched["is_asian"], "population_group"] = "Asian"
    enriched.loc[~enriched["race_reported"], "population_group"] = "Unknown"

    added_columns = [
        "race",
        "ethnicity",
        "population_group",
        "race_reported",
        "is_asian",
    ]
    original_columns = [column for column in basic.columns if column not in added_columns]
    enriched = enriched[original_columns + added_columns]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.patient_output.parent.mkdir(parents=True, exist_ok=True)
    enriched.to_parquet(args.output, index=False, compression="zstd")
    patient.to_parquet(args.patient_output, index=False, compression="zstd")

    print("\nPopulation metadata by sample:")
    print(enriched["population_group"].value_counts(dropna=False).to_string())

    lusc = enriched[enriched["tissue_type"].eq("LUSC")]
    if not lusc.empty:
        print("\nLUSC samples by class and population group:")
        print(
            pd.crosstab(
                lusc["sample_class"],
                lusc["population_group"],
                margins=True,
            ).to_string()
        )

    coverage = enriched["race_reported"].mean() if len(enriched) else float("nan")
    print(f"\nRace annotation coverage: {coverage:.1%}")
    print(f"Saved sample metadata: {args.output}  shape={enriched.shape}")
    print(f"Saved patient metadata: {args.patient_output}  shape={patient.shape}")


if __name__ == "__main__":
    main()
