"""
05b_merge_population_summary.py
--------------------------------------------------
Merges the cohort/mode files generated by
04b_methy_summary_population.py into the PostgreSQL input table.

Input:
    data/summary_population/*_summary.parquet

Output:
    data/raw/methylation_summary_population.parquet
--------------------------------------------------
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parent.parent
INPUT_DIR = ROOT / "data" / "summary_population"
OUTPUT_PATH = ROOT / "data" / "raw" / "methylation_summary_population.parquet"

KEY_COLUMNS = [
    "site_id",
    "tumor_type",
    "population_mode",
    "pan_reference_mode",
]

OUTPUT_COLUMNS = KEY_COLUMNS + [
    "tumor_median",
    "tumor_std",
    "tumor_n",
    "tumor_total_samples",
    "normal_median",
    "normal_std",
    "normal_n",
    "normal_total_samples",
    "pan_tumor_median",
    "pan_tumor_std",
    "pan_tumor_n",
    "pan_tumor_total_samples",
    "pan_normal_median",
    "pan_normal_std",
    "pan_normal_n",
    "pan_normal_total_samples",
    "delta_median",
    "hi_index",
    "dispersion_index",
]

INTEGER_COLUMNS = [
    "tumor_n",
    "tumor_total_samples",
    "normal_n",
    "normal_total_samples",
    "pan_tumor_n",
    "pan_tumor_total_samples",
    "pan_normal_n",
    "pan_normal_total_samples",
]

FLOAT_COLUMNS = [
    "tumor_median",
    "tumor_std",
    "normal_median",
    "normal_std",
    "pan_tumor_median",
    "pan_tumor_std",
    "pan_normal_median",
    "pan_normal_std",
    "delta_median",
    "hi_index",
    "dispersion_index",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge population methylation summary parquet files."
    )
    parser.add_argument("--input-dir", type=Path, default=INPUT_DIR)
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    files = sorted(args.input_dir.glob("*_summary.parquet"))
    if not files:
        raise FileNotFoundError(
            f"No population summary files were found in {args.input_dir}."
        )

    frames: list[pd.DataFrame] = []
    for path in files:
        print(f"Loading: {path.name}")
        frame = pd.read_parquet(path)
        missing = sorted(set(OUTPUT_COLUMNS).difference(frame.columns))
        if missing:
            raise KeyError(f"{path.name} is missing columns: {missing}")
        frames.append(frame[OUTPUT_COLUMNS].copy())

    merged = pd.concat(frames, ignore_index=True)

    duplicate_mask = merged.duplicated(KEY_COLUMNS, keep=False)
    if duplicate_mask.any():
        examples = merged.loc[duplicate_mask, KEY_COLUMNS].head(10)
        raise ValueError(
            "Duplicate population summary keys were found:\n"
            + examples.to_string(index=False)
        )

    for column in KEY_COLUMNS:
        merged[column] = merged[column].astype("string")
    for column in INTEGER_COLUMNS:
        merged[column] = pd.to_numeric(merged[column], errors="coerce").astype("Int32")
    for column in FLOAT_COLUMNS:
        merged[column] = pd.to_numeric(merged[column], errors="coerce").astype("float32")

    merged = merged.sort_values(KEY_COLUMNS).reset_index(drop=True)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    merged.to_parquet(args.output, index=False, compression="zstd")

    print(f"\nSaved: {args.output}")
    print(f"Shape: {merged.shape}")
    print("Rows by cohort and population mode:")
    print(
        merged.groupby(
            ["tumor_type", "population_mode", "pan_reference_mode"],
            observed=True,
        ).size().to_string()
    )


if __name__ == "__main__":
    main()
