"""
15_add_sequence_features_to_regions_v2.py
--------------------------------------------------

Add tumor-independent DNA sequence features to gene
CpG regions using a local reference FASTA.

Purpose
-------
To annotate each gene region with local sequence context and
calculate a reproducible sequence_score. This score captures the
sequence composition of the region and can be combined downstream
with tumor-specific methylation, expression, leukocyte background,
and biological evidence.

Inputs
------
- data/biomarkers/biomarker_region.parquet
- Local uncompressed reference FASTA passed with --fasta

Processing
----------
1. Load the gene region table generated by pipeline 14.
2. Open or create a minimal FASTA index (.fai).
3. Extract the core or browser interval for each region.
4. Count C, G, CG and GCGC motifs.
5. Calculate GC fraction, CG density and GCGC density.
6. Combine sequence metrics into a robustly normalized
   sequence_score.
7. Export one sequence-feature row per region_id.

Outputs
-------
- data/biomarkers/biomarker_region_sequence_score.parquet
- data/biomarkers/biomarker_region_sequence_score_config.json

Score
-----
sequence_score = 100 * (
    0.35 * normalized CG density
  + 0.30 * normalized GCGC density
  + 0.20 * GC fraction
  + 0.15 * normalized manifest CpG density
)

Notes
-----
The FASTA genome build must match the manifest coordinates.

--------------------------------------------------
"""

from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "data" / "biomarkers"


def normalize_chrom(chrom: Any, fasta_names: set[str]) -> str | None:
    raw = str(chrom).strip().replace("CHR", "chr")
    candidates = [raw]
    if raw.startswith("chr"):
        candidates.append(raw.replace("chr", "", 1))
    else:
        candidates.append("chr" + raw)
    for c in candidates:
        if c in fasta_names:
            return c
    return None


def count_overlapping_motif(sequence: str, motif: str) -> int:
    if not sequence:
        return 0
    return len(re.findall(f"(?={re.escape(motif.upper())})", sequence.upper()))


def build_fai(fasta_path: Path) -> Path:
    """Create a minimal .fai index for an uncompressed FASTA."""
    fai_path = fasta_path.with_suffix(fasta_path.suffix + ".fai")
    print(f"Creating FASTA index: {fai_path}")
    records = []
    with open(fasta_path, "rb") as handle:
        name = None
        length = 0
        seq_offset = None
        line_bases = None
        line_width = None

        while True:
            pos = handle.tell()
            line = handle.readline()
            if not line:
                if name is not None:
                    records.append((name, length, seq_offset, line_bases, line_width))
                break

            if line.startswith(b">"):
                if name is not None:
                    records.append((name, length, seq_offset, line_bases, line_width))
                name = line[1:].decode("utf-8", errors="ignore").strip().split()[0]
                length = 0
                seq_offset = None
                line_bases = None
                line_width = None
            else:
                stripped = line.rstrip(b"\r\n")
                if seq_offset is None:
                    seq_offset = pos
                    line_bases = len(stripped)
                    line_width = len(line)
                length += len(stripped)

    with open(fai_path, "w", encoding="utf-8") as out:
        for rec in records:
            out.write("\t".join(map(str, rec)) + "\n")
    return fai_path


class IndexedFasta:
    def __init__(self, fasta_path: Path):
        if fasta_path.suffix == ".gz":
            raise ValueError("Compressed .gz FASTA is not supported by this lightweight reader. Use an uncompressed .fa/.fasta.")
        self.fasta_path = fasta_path
        self.fai_path = fasta_path.with_suffix(fasta_path.suffix + ".fai")
        if not self.fai_path.exists():
            build_fai(fasta_path)
        self.index = self._load_index()
        self.names = set(self.index.keys())
        self.handle = open(fasta_path, "rb")

    def _load_index(self) -> dict[str, tuple[int, int, int, int]]:
        index = {}
        with open(self.fai_path, "r", encoding="utf-8") as handle:
            for line in handle:
                fields = line.rstrip("\n").split("\t")
                if len(fields) < 5:
                    continue
                name, length, offset, line_bases, line_width = fields[:5]
                index[name] = (int(length), int(offset), int(line_bases), int(line_width))
        return index

    def fetch(self, chrom: str, start: int, end: int) -> str:
        """Fetch 1-based inclusive interval."""
        if chrom not in self.index:
            raise KeyError(f"Chromosome not in FASTA: {chrom}")
        length, offset, line_bases, line_width = self.index[chrom]
        start = max(1, int(start))
        end = min(int(end), length)
        if end < start:
            return ""

        zero = start - 1
        n_bases = end - start + 1
        file_pos = offset + (zero // line_bases) * line_width + (zero % line_bases)
        n_lines = math.ceil(((zero % line_bases) + n_bases) / line_bases)
        n_bytes = n_bases + n_lines + 2
        self.handle.seek(file_pos)
        chunk = self.handle.read(n_bytes)
        seq = re.sub(rb"\s+", b"", chunk).decode("ascii", errors="ignore")[:n_bases]
        return seq.upper()

    def close(self) -> None:
        self.handle.close()


def robust_quantile_norm(values: pd.Series, upper_quantile: float = 0.95) -> pd.Series:
    x = pd.to_numeric(values, errors="coerce")
    if x.notna().sum() == 0:
        return pd.Series(np.zeros(len(x), dtype=np.float32), index=x.index)
    q = float(x.quantile(upper_quantile))
    if not np.isfinite(q) or q <= 0:
        return pd.Series(np.zeros(len(x), dtype=np.float32), index=x.index)
    return (x / q).clip(0, 1).fillna(0).astype(np.float32)


def compute_sequence_score(df: pd.DataFrame) -> pd.Series:
    cg_norm = robust_quantile_norm(df["cg_density_per_100bp"])
    gcgc_norm = robust_quantile_norm(df["gcgc_density_per_100bp"])
    gc_norm = pd.to_numeric(df["gc_fraction"], errors="coerce").clip(0, 1).fillna(0)
    manifest_norm = robust_quantile_norm(df["manifest_cpg_density_per_100bp"])
    score = 100 * (0.35 * cg_norm + 0.30 * gcgc_norm + 0.20 * gc_norm + 0.15 * manifest_norm)
    return score.astype(np.float32)


def add_sequence_features(regions: pd.DataFrame, fasta_path: Path, sequence_region: str, limit: int | None = None) -> pd.DataFrame:
    required = ["region_id", "chr", "core_start", "core_end", "browser_start", "browser_end", "cpg_density_per_100bp"]
    missing = [c for c in required if c not in regions.columns]
    if missing:
        raise ValueError(f"Missing required columns in regions: {missing}")

    work = regions.copy()
    if limit is not None and limit > 0:
        work = work.head(limit).copy()

    fasta = IndexedFasta(fasta_path)
    records = []

    try:
        for i, row in work.reset_index(drop=True).iterrows():
            chrom = normalize_chrom(row["chr"], fasta.names)
            if chrom is None:
                records.append({"region_id": row["region_id"], "sequence_available": False, "sequence_error": "chrom_not_found"})
                continue

            if sequence_region == "browser":
                start, end = int(row["browser_start"]), int(row["browser_end"])
            else:
                start, end = int(row["core_start"]), int(row["core_end"])

            try:
                seq = fasta.fetch(chrom, start, end)
            except Exception as exc:
                records.append({"region_id": row["region_id"], "sequence_available": False, "sequence_error": str(exc)[:200]})
                continue

            if not seq:
                records.append({"region_id": row["region_id"], "sequence_available": False, "sequence_error": "empty_sequence"})
                continue

            length = len(seq)
            n_c = seq.count("C")
            n_g = seq.count("G")
            n_cg = count_overlapping_motif(seq, "CG")
            n_gcgc = count_overlapping_motif(seq, "GCGC")
            gc_fraction = (n_c + n_g) / length if length else np.nan

            records.append({
                "region_id": row["region_id"],
                "gene_symbol": row.get("gene_symbol"),
                "chr": row.get("chr"),
                "sequence_region": sequence_region,
                "sequence_start": start,
                "sequence_end": end,
                "sequence_available": True,
                "sequence_error": "",
                "sequence_length": length,
                "n_c_sequence": n_c,
                "n_g_sequence": n_g,
                "n_cg_sequence": n_cg,
                "n_gcgc": n_gcgc,
                "gc_fraction": gc_fraction,
                "cg_density_per_100bp": n_cg / length * 100 if length else np.nan,
                "gcgc_density_per_100bp": n_gcgc / length * 100 if length else np.nan,
                "manifest_cpg_density_per_100bp": row.get("cpg_density_per_100bp", np.nan),
            })

            if (i + 1) % 10000 == 0:
                print(f"  Processed {i + 1:,} regions")
    finally:
        fasta.close()

    out = pd.DataFrame(records)
    for col in [
        "sequence_length", "n_c_sequence", "n_g_sequence", "n_cg_sequence", "n_gcgc",
        "gc_fraction", "cg_density_per_100bp", "gcgc_density_per_100bp", "manifest_cpg_density_per_100bp",
    ]:
        if col not in out.columns:
            out[col] = np.nan

    out["sequence_score"] = compute_sequence_score(out)
    return out


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Add sequence features to region universe from a local FASTA.")
    parser.add_argument("--regions", type=Path, default=OUT_DIR / "biomarker_region.parquet")
    parser.add_argument("--fasta", type=Path, required=True, help="Local uncompressed reference FASTA, e.g. data/reference/hg38.fa")
    parser.add_argument("--output", type=Path, default=OUT_DIR / "biomarker_region_sequence_score.parquet")
    parser.add_argument("--sequence-region", choices=["core", "browser"], default="core")
    parser.add_argument("--limit", type=int, default=0, help="Optional debug limit. 0 means all regions.")
    parser.add_argument("--write-csv", action="store_true", help="Optional diagnostic CSV copy. Off by default.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.regions.exists():
        raise FileNotFoundError(f"Missing regions file: {args.regions}")
    if not args.fasta.exists():
        raise FileNotFoundError(f"Missing FASTA file: {args.fasta}")

    print(f"Loading regions: {args.regions}")
    regions = pd.read_parquet(args.regions)
    limit = args.limit if args.limit and args.limit > 0 else None

    print(f"Adding sequence features from FASTA: {args.fasta}")
    features = add_sequence_features(regions, args.fasta, args.sequence_region, limit=limit)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    features.to_parquet(args.output, index=False, compression="zstd")

    csv_path = None
    if args.write_csv:
        csv_path = args.output.with_suffix(".csv")
        features.to_csv(csv_path, index=False)

    config_path = args.output.with_name(args.output.stem + "_config.json")
    config = {
        "regions": str(args.regions),
        "fasta": str(args.fasta),
        "output": str(args.output),
        "sequence_region": args.sequence_region,
        "limit": args.limit,
        "rows": int(features.shape[0]),
        "sequence_available": int(features["sequence_available"].sum()) if "sequence_available" in features.columns else 0,
        "write_csv": bool(args.write_csv),
        "csv_path": str(csv_path) if csv_path else None,
    }
    config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")

    n_available = int(features["sequence_available"].sum()) if "sequence_available" in features.columns else 0
    max_score = float(pd.to_numeric(features.get("sequence_score", pd.Series(dtype=float)), errors="coerce").max()) if not features.empty else float("nan")
    print("\nSequence diagnostics:")
    print(f"  sequence_available: {n_available:,}/{features.shape[0]:,}")
    print(f"  max sequence_score: {max_score:.3f}")
    if "sequence_error" in features.columns and n_available == 0:
        print("  Top sequence errors:")
        print(features["sequence_error"].value_counts(dropna=False).head(10).to_string())

    print("\nSaved outputs:")
    print(f"  Region sequence score:   {args.output}  shape={features.shape}")
    if csv_path:
        print(f"  CSV copy:                 {csv_path}")
    print(f"  Config:                   {config_path}")


if __name__ == "__main__":
    main()
